import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers';
import { Navigation } from "@repo/ui/components/zone-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Navigation />
          {children}
          <footer className="bg-gray-100 mt-20 py-8 text-center text-gray-600">
            <p>© 2026 Apple Multi-Zone Demo. All rights reserved.</p>
            <p className="text-sm mt-2">This is the <strong>Home Zone</strong> (Port 3000)</p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
